#!/usr/bin/env bash
#TODO(by black7375)
#However, there may be existing user's settings, so back up and make a copy.
#I just made a simple one yesterday, assuming that there may be multiple backup states.
#I think it's better to do a redirection(>>) after backup to merge the contents of the file.
printf "Are you using ESR, Default, or Dev?(ESR/Default/Dev): "
read -r
if [ "$REPLY" == "ESR" ] || [ "$REPLY" == "esr" ]; then
  profiledir="$(grep '.default-esr' ~/.mozilla/firefox/profiles.ini | grep 'Default=' | cut -f 2 -d'=')"
elif [ "$REPLY" == "Default" ] || [ "$REPLY" == "default" ]; then
  profiledir="$(grep '.default-release' ~/.mozilla/firefox/profiles.ini | grep 'Default=' | cut -f 2 -d'=')"
elif [ "$REPLY" == "Dev" ] || [ "$REPLY" == "dev" ]; then
  profiledir="$(grep '.dev-edition-default' ~/.mozilla/firefox/profiles.ini | grep 'Default=' | cut -f 2 -d'=')"
else
  echo "Unspecified."
  exit
fi
if [[ -f ~/.mozilla/firefox/${profiledir}/user.js ]]; then
    printf "user.js exists. Do you want to make a backup of it?(Y/n): "
    read -r
    if [ "N" == "$REPLY" ] || [ "n" == "$REPLY" ]; then
      printf "Overwriting...\n"
      rm -rf ~/.mozilla/firefox/"${profiledir}"/user.js
      cp user.js ~/.mozilla/firefox/"${profiledir}"/user.js
    else
      printf "Making a backup...\n"
      if [[ -d "$HOME/.mozilla/firefox/${profiledir}/backup" ]]; then
        rm -rf ~/.mozilla/firefox/"${profiledir}"/backup
      fi
      mkdir ~/.mozilla/firefox/"${profiledir}"/backup/
      mv ~/.mozilla/firefox/"${profiledir}"/user.js ~/.mozilla/firefox/"${profiledir}"/backup/user.js
      cp user.js ~/.mozilla/firefox/"${profiledir}"/user.js
    fi
    else
      cp user.js ~/.mozilla/firefox/"${profiledir}"/user.js
fi
if [[ -d "$HOME/.mozilla/firefox/${profiledir}/chrome" ]]; then
  printf "The directory chrome/ exists. Do you want to make a backup of it?(Y/n): "
  read -r
  if [ "N" == "$REPLY" ] || [ "n" == "$REPLY" ]; then
    printf"Overwriting...\n"
    rm -rf ~/.mozilla/firefox/"${profiledir}"/chrome
    mkdir ~/.mozilla/firefox/"${profiledir}"/chrome
    cp userChrome.css ~/.mozilla/firefox/"${profiledir}"/chrome/userChrome.css
    cp userContent.css ~/.mozilla/firefox/"${profiledir}"/chrome/userContent.css
    cp -r icons ~/.mozilla/firefox/"${profiledir}"/chrome/
    printf "\nInstallation finished."
  else
    printf "Making a backup...\n"
    if [[ -d "$HOME/.mozilla/firefox/${profiledir}/backup/chrome" ]]; then
      rm -rf ~/.mozilla/firefox/"${profiledir}"/backup/chrome
    fi
    if [[ -d "$HOME/.mozilla/firefox/${profiledir}/backup" ]]; then
      mkdir ~/.mozilla/firefox/"${profiledir}"/backup/chrome
      mv ~/.mozilla/firefox/"${profiledir}"/chrome ~/.mozilla/firefox/"${profiledir}"/backup/chrome
      mkdir ~/.mozilla/firefox/"${profiledir}"/chrome
      cp userChrome.css ~/.mozilla/firefox/"${profiledir}"/chrome/userChrome.css
      cp userContent.css ~/.mozilla/firefox/"${profiledir}"/chrome/userContent.css
      cp -r icons ~/.mozilla/firefox/"${profiledir}"/chrome/
      printf "\nInstallation finished."
    else
      mkdir ~/.mozilla/firefox/"${profiledir}"/backup
      mv ~/.mozilla/firefox/"${profiledir}"/chrome ~/.mozilla/firefox/"${profiledir}"/backup/chrome
      mkdir ~/.mozilla/firefox/"${profiledir}"/chrome
      cp userChrome.css ~/.mozilla/firefox/"${profiledir}"/chrome/userChrome.css
      cp userContent.css ~/.mozilla/firefox/"${profiledir}"/chrome/userContent.css
      cp -r icons ~/.mozilla/firefox/"${profiledir}"/chrome/
      printf "\nInstallation finished."
    fi
    
  fi
  else
    mkdir ~/.mozilla/firefox/"${profiledir}"/chrome
    cp userChrome.css ~/.mozilla/firefox/"${profiledir}"/chrome/userChrome.css
    cp userContent.css ~/.mozilla/firefox/"${profiledir}"/chrome/userContent.css
    cp -r icons ~/.mozilla/firefox/"${profiledir}"/chrome/
    printf "\nInstallation finished."
fi

